// <auto-generated />
using System;
using Final_Cordero_Raura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Cordero_Raura.Migrations
{
    [DbContext(typeof(Final_Cordero_RauraContext))]
    [Migration("20230502182940_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Final_Cordero_Raura.Models.Pelicula", b =>
                {
                    b.Property<int>("IdPelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPelicula"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.HasKey("IdPelicula");

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("Final_Cordero_Raura.Models.Resena", b =>
                {
                    b.Property<int>("IdResena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResena"), 1L, 1);

                    b.Property<int>("IdPelicula")
                        .HasColumnType("int");

                    b.Property<int?>("PeliculaIdPelicula")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCedula")
                        .HasColumnType("int");

                    b.HasKey("IdResena");

                    b.HasIndex("PeliculaIdPelicula");

                    b.HasIndex("UsuarioCedula");

                    b.ToTable("Resena");
                });

            modelBuilder.Entity("Final_Cordero_Raura.Models.Usuario", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cedula"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Final_Cordero_Raura.Models.Resena", b =>
                {
                    b.HasOne("Final_Cordero_Raura.Models.Pelicula", "Pelicula")
                        .WithMany("Resenas")
                        .HasForeignKey("PeliculaIdPelicula");

                    b.HasOne("Final_Cordero_Raura.Models.Usuario", null)
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioCedula");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Final_Cordero_Raura.Models.Pelicula", b =>
                {
                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Final_Cordero_Raura.Models.Usuario", b =>
                {
                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
